# BASE UI
ColorColumn: '- line'
Conceal: ''
Cursor: 'grey'
CursorIM: ''
CursorColumn: '- line'
CursorLine: '- line'
Directory: ''
DiffAdd: 'green gutter b'
DiffChange: 'amber gutter b'
DiffDelete: 'red gutter b'
DiffText: 'foreground gutter'
ErrorMsg: 'red'
VertSplit: 'line line'
Folded: ''
FoldColumn: ''
SignColumn: 'foreground gutter'
IncSearch: ''
LineNr: 'lineNumber gutter'
CursorLineNr: 'amber gutter b'
MatchParen: 'background foreground'
ModeMsg: ''
MoreMsg: ''
NonText: 'foreground'
Normal: 'foreground background'
PMenu: 'grey deepPurple'
PMenuSel: 'deepPurple grey b'
PmenuSbar: ''
PmenuThumb: ''
Question: ''
Search: ''
SpecialKey: ''
SpellBad: ''
SpellLocal: ''
SpellCap: ''
SpellRare: ''
StatusLine: ''
StatusLineNC: ''
TabLine: 'foreground backgroundLight'
TabLineFill: 'foreground gutter'
TabLineSel: 'foreground deepPurple'
Title: ''
Visual: '- violet'
VisualNOS: ''
WarningMsg: ''
WildMenu: ''
# BASE SYNTAX
Comment: 'teal'
Constant: 'brightTeal'
String: 'pink' # Constant
Character: '' # Constant
Boolean: 'orange' # Constant
Number: 'aqua' # Constant
Float: 'aqua' # Constant
Identifier: 'yellow'
Function: 'blue' # Identifier
Statement: 'red'
Conditional: 'yellow' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'green' # Statement
Keyword: 'aqua' # Statement
Exception: '' # Statement
PreProc: 'yellow'
Include: '' # PreProc
#Define: 'green' # PreProc
Define: 'purple' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'amber'
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'orange'
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: 'red'
Todo: 'indigo amber b'
